// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfVv2V1etVDshnPlauUoNsPrwoTtUwIxg',
    appId: '1:810487599580:web:9037676c51227a42e37f19',
    messagingSenderId: '810487599580',
    projectId: 'kinli-171dc',
    authDomain: 'kinli-171dc.firebaseapp.com',
    storageBucket: 'kinli-171dc.firebasestorage.app',
    measurementId: 'G-S6VJ878T3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMgWfrvsaVX3OkLKQczsuzYsXmQrD8oNY',
    appId: '1:810487599580:android:927edbaa9530d65be37f19',
    messagingSenderId: '810487599580',
    projectId: 'kinli-171dc',
    storageBucket: 'kinli-171dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcOcE26peetQuJu7KfJinzinBLsysz1Sg',
    appId: '1:810487599580:ios:b595f05321304abce37f19',
    messagingSenderId: '810487599580',
    projectId: 'kinli-171dc',
    storageBucket: 'kinli-171dc.firebasestorage.app',
    iosBundleId: 'com.example.kinli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcOcE26peetQuJu7KfJinzinBLsysz1Sg',
    appId: '1:810487599580:ios:b595f05321304abce37f19',
    messagingSenderId: '810487599580',
    projectId: 'kinli-171dc',
    storageBucket: 'kinli-171dc.firebasestorage.app',
    iosBundleId: 'com.example.kinli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfVv2V1etVDshnPlauUoNsPrwoTtUwIxg',
    appId: '1:810487599580:web:54be904e88f94458e37f19',
    messagingSenderId: '810487599580',
    projectId: 'kinli-171dc',
    authDomain: 'kinli-171dc.firebaseapp.com',
    storageBucket: 'kinli-171dc.firebasestorage.app',
    measurementId: 'G-SMP3CVVD0X',
  );
}
