
import 'package:flutter/material.dart'; //library, Implements Google design system as ready-to-use widgets
import 'package:flutter_riverpod/flutter_riverpod.dart'; //state management library.
import 'package:firebase_core/firebase_core.dart'; //Needed to initialize Firebase before using Firestore, Auth, or other Firebase services.
import 'firebase_options.dart'; // auto-generated by FlutterFire CLI
import 'app.dart';

void main() async {
  //Ensures Flutter is fully set up before running asynchronous code (like Firebase initialization)
  WidgetsFlutterBinding.ensureInitialized();

  //This connects app to the Firebase project so I can use Firestore, Auth, etc.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  //ProviderScope wraps app, makes Riverpod providers available everywhere in the widget tree.
  //KinliApp (from app.dart) is the root widget
  runApp(const ProviderScope(child: KinliApp()));
}
